name: Ec2 Creation
on: [push]
jobs:
  terraform:
    runs-on: ubuntu-latest 
    steps:
      - name: checkout code 
        uses: actions/checkout@v6
      - name: terraform setup 
        uses: hashicorp/setup-terraform@v4
      - name: terraform init
        run: terraform init
      # - name: run plan
      #   run: terraform plan
      - name: Configure AWS Credentials via Static Keys
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: run plan
        run: terraform plan